### ISSUE TITLE
breaking changes in minor release

### ISSUE THREAD

**Issue by BarryThePenguin** [elwayman02/ember-sinon-qunit#193]
👋🏻 thanks for this addon, it's super easy to integrate sinon with ember + qunit tests.

I haven't run into the issue personally, but it looks like `v3.4.0` which was released recently introduced a breaking change where `sinon` was updated from `v6` to `v7`.

I think the difference the between breaking vs minor changes is a little mirky here so I don't want to get too bogged down in the specifics... I do want to help make this less of an issue for people upgrading in the near future!

Have you considered making `sinon` a `peerDependency` for this addon? That way consumers can pick and choose the version they want to use. It would require consumers install both `ember-sinon-qunit` and `sinon`. I can put up a PR with an example of how this would work?

**Comment by elwayman02** [comment]
Thanks for calling this out! `ember-sinon-qunit` doesn't directly require any version of Sinon and only includes it as a devDependency. However, it gets a Sinon requirement through [ember-sinon](https://github.com/csantero/ember-sinon/releases/tag/3.0.0), which released a major version back in November for Sinon 7. I did not realize when making this release that it was the first release we'd done that included v3.x of ember-sinon, so that's my bad.

As far as making it a `peerDependency`, that's not impossible, though in general the only improvements we make to `ember-sinon-qunit` with new versions are to incorporate new Sinon functionality. So for the most part, it wouldn't make sense to use a new version of this library with an old version of Sinon. That said, it would be possible to do this by introducing guards into this library that make it compatible with both the old and new versions of Sinon's APIs. This isn't something I currently plan to support, as it would add a much larger maintenance load for a project that only has a single maintainer currently. If there is a strong need for this, I'd be happy to consider contributions to make this possible (and I'm always looking for more maintainers).

I'll release a major version to correct this mistake and try to make a note somewhere to myself to avoid this happening in the future. Sorry for any pain it might have caused!

**Comment by BarryThePenguin** [comment]
No worries! Thanks for the response 👍🏻
