### ISSUE TITLE
Support for wrapping moduleFor

### ISSUE THREAD

**Issue by arjansingh** [elwayman02/ember-sinon-qunit#6]
Love the add-on. Do you have any plans add support for using sinon in `moduleFor` as well?

**Comment by elwayman02** [comment]
@arjansingh sorry for the slow reply, the holidays were super busy! Can you explain what you would want to use sinon for in `moduleFor`? The point of this addon is to encapsulate each `test()` method, so that setup/teardown can be ensured. I'm not sure what you would want this addon to do in terms of `moduleFor`...

**Comment by arjansingh** [comment]
Sometimes it is more useful to set up stubs and mocks in the `beforeEach` setup function (e.g, they all use the same stubbed service). 

Currently you would have to copy/paste the stubs in each test block. Being able to access sinon methods in `moduleFor` would allow you define all of your common stubs in one place.

**Comment by elwayman02** [comment]
@arjansingh I'm not sure how that would work. The point of this addon is to wrap each `test` method in its own sandbox environment. I'm not entirely certain how one would extend that context to the `beforeEach` method (and have a different context every time it gets executed). If you have an idea on how to accomplish that, I welcome a PR.

Alternatively, you can use a helper method to accomplish DRY code:

```
let component, stub;

moduleForComponent('blah', {
  beforeEach() {
    component = this.subject();
  }
});

function setupStub() {
  stub = this.stub(component, 'methodOne');
}

test('methodTwo', function (assert) {
  setupStub.call(this);
  component.methodTwo();
  assert.ok(stub.calledOnce, 'methodName was called once');
});

test('methodThree', function (assert) {
  setupStub.call(this);
  component.methodThree();
  assert.ok(stub.calledOnce, 'methodName was called once');
});
```

**Comment by sukima** [comment]
The use case is for when you want to stub out an object on _every_ test without having to repeat yourself. As previously explained this could be done by calling a `setupStub` function in every test. But it can also be done using sinon's `sandbox()` API:

```javascript
const sandbox = sinon.sandbox.create();

moduleFor('foo:bar', 'foo | bar', {
  beforeEach() {
    sandbox.stub(component, 'methodOne');
  },
  afterEach() {
    sandbox.restore();
  }
});

test('lorem ipsum', function (assert) {
  assert.expect(1);
  component.methodOne();
  sinon.assert.calledOnce(component.methodOne);
});
```

**Comment by elwayman02** [comment]
@sukima your suggestion doesn't utilize anything this addon is doing, so I don't see how that addresses the implementation question I had. Yes, you can use sinon directly without using this addon; the point of this addon is simply making it easier. One of the main reasons this addon exists is to avoid having to do explicit cleanup with `sandbox.restore()` in every `afterEach`, for example.

What I'm saying is that I don't think there's a way to incorporate the `beforeEach` because the sinon sandbox provided by this addon is wrapped explicitly around the callback function of `test`. That said, maybe someone like @rwjblue knows more about this and there's a hook I'm missing that easily connects `beforeEach` and `test` where I could put the context of the sandbox into `beforeEach`.

**Comment by elwayman02** [comment]
Closing in favor of #25, which has a failing test
